#!/bin/bash

set -o nounset
set -o errexit

REPOPATH=`pwd`
TMPDIR=`mktemp -d`
cd $TMPDIR
git clone $REPOPATH $TMPDIR
cp -r /vagrant/master_repo/test $TMPDIR
cd $TMPDIR
test/score
echo
cd ..
rm -fr $TMPDIR
